### ISSUE TITLE
access token 存文件吧 不然历史记录里面全是 token

### ISSUE THREAD

**Issue by zhuangya** [rrfeng/ossuploader#1]
想安全可以 pgp 一下嘛

**Comment by rrfeng** [comment]
嗯

**Comment by rrfeng** [comment]
命令行里也要干掉……

**Comment by rrfeng** [comment]
https://github.com/rrfeng/ossuploader/commit/30c13f667766615ed323ade5c632af04914313c9

默认从 ~/.ossuploader/config.json 读配置。
